version: '3.4'

services:
  wallabagbot:
    image: wallabagbot
    container_name: wallabagbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file: .env
